<?php include 'header.phtml'; ?>
	<div class="seccion">
		<form class="login">
			<table>
				<tr>
					<th><h4>Acerca de</h4></th>
				</tr>
				<tr>
					<th>Mini-Aplicacion</th>
				</tr>
				<tr>
					<th>
						<p>Desarrolla por el <a href="contactos.html">Equipo</a>
							<br>
							en busca de una nota para la materia:
							<br>
							"Sistemas Distribuidos"
						</p>
						
					</th>
				</tr>
			</table>
		</form>
	</div>
<?php include 'footer.phtml'; ?>