<?php include 'header.phtml'; ?>
	<div class="seccion">
		<form class="login">
			<table>
				<tr>
					<th><h4>Equipo</h4></th>
				</tr>
				<tr>
					<th>Erika Alvarez CI: 24.792.772</th>
				</tr>
				<tr>
					<th>Daniel Delgado CI: 20.586.579</th>
				</tr>
				<tr>
					<th>Erick Moreno CI: 21.272.301</th>
				</tr>
				
			</table>
		</form>
	</div>
<?php include 'footer.phtml'; ?>