<html>
<head>
	<title>Mini-Aplicaci&oacute;n</title>
	<link rel="stylesheet" type="text/css" href="static/css/estilo.css">
	<link rel="stylesheet" type="text/css" href="../static/css/estilo.css">
</head>
<!--Cuerpo de la pagina-->
<body>
	<div class="container">
	<header class="cabeza">
		<div class="logo">
			<img src="">
		</div>
		<nav class="menu">
			<a class="navlink" href="/Aplicacion/index.php"><span class="nav-btn">Inicio</span></a>
			<a class="navlink" href="/Aplicacion/templates/registro.phtml"><span class="nav-btn">Registro</span></a>
			<a class="navlink" href="/Aplicacion/templates/acerca.phtml"><span class="nav-btn">Acerca de</span></a>
			<a class="navlink" href="/Aplicacion/templates/contactos.phtml"><span class="nav-btn">Contactos</span></a>
		</nav>
	</header>