<?php include 'header.phtml'; ?>
	<div class="centro">
		<img src="">
	</div>
	<div class="seccion">
		<form class="login">
			<table>
				<tr>
					<th colspan="2"><h4>Ingresar</h4></th>
				</tr>
				<tr>
					<th><input type="text" name="usuario" placeholder="Usuario" required></th>
					<th><input type="password" name="clave" placeholder="Clave" required></th>
				</tr>
				<tr>
					
				</tr>
				<tr>
					<th colspan="2"><input type="submit" value="Ingresar"></th>
				</tr>
			</table>
		</form>
	</div>
<?php include 'footer.phtml'; ?>